/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings/index";
import { Route as ProductExportIndexRouteImport } from "./routes/product-export/index";
import { Route as ProductDescriptionIndexRouteImport } from "./routes/product-description/index";
import { Route as ProductExportNewRouteImport } from "./routes/product-export/new";
import { Route as ProductExportIdRouteImport } from "./routes/product-export/$id";
import { Route as ProductDescriptionNewRouteImport } from "./routes/product-description/new";
import { Route as ErrorsOfflineRouteImport } from "./routes/errors/offline";
import { Route as Errors500RouteImport } from "./routes/errors/500";
import { Route as Errors404RouteImport } from "./routes/errors/404";
import { Route as Errors403RouteImport } from "./routes/errors/403";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductExportIndexRoute = ProductExportIndexRouteImport.update({
  id: "/product-export/",
  path: "/product-export/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductDescriptionIndexRoute = ProductDescriptionIndexRouteImport.update({
  id: "/product-description/",
  path: "/product-description/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductExportNewRoute = ProductExportNewRouteImport.update({
  id: "/product-export/new",
  path: "/product-export/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductExportIdRoute = ProductExportIdRouteImport.update({
  id: "/product-export/$id",
  path: "/product-export/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductDescriptionNewRoute = ProductDescriptionNewRouteImport.update({
  id: "/product-description/new",
  path: "/product-description/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ErrorsOfflineRoute = ErrorsOfflineRouteImport.update({
  id: "/errors/offline",
  path: "/errors/offline",
  getParentRoute: () => rootRouteImport,
} as any);
const Errors500Route = Errors500RouteImport.update({
  id: "/errors/500",
  path: "/errors/500",
  getParentRoute: () => rootRouteImport,
} as any);
const Errors404Route = Errors404RouteImport.update({
  id: "/errors/404",
  path: "/errors/404",
  getParentRoute: () => rootRouteImport,
} as any);
const Errors403Route = Errors403RouteImport.update({
  id: "/errors/403",
  path: "/errors/403",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/errors/403": typeof Errors403Route;
  "/errors/404": typeof Errors404Route;
  "/errors/500": typeof Errors500Route;
  "/errors/offline": typeof ErrorsOfflineRoute;
  "/product-description/new": typeof ProductDescriptionNewRoute;
  "/product-export/$id": typeof ProductExportIdRoute;
  "/product-export/new": typeof ProductExportNewRoute;
  "/product-description/": typeof ProductDescriptionIndexRoute;
  "/product-export/": typeof ProductExportIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/errors/403": typeof Errors403Route;
  "/errors/404": typeof Errors404Route;
  "/errors/500": typeof Errors500Route;
  "/errors/offline": typeof ErrorsOfflineRoute;
  "/product-description/new": typeof ProductDescriptionNewRoute;
  "/product-export/$id": typeof ProductExportIdRoute;
  "/product-export/new": typeof ProductExportNewRoute;
  "/product-description": typeof ProductDescriptionIndexRoute;
  "/product-export": typeof ProductExportIndexRoute;
  "/settings": typeof SettingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/errors/403": typeof Errors403Route;
  "/errors/404": typeof Errors404Route;
  "/errors/500": typeof Errors500Route;
  "/errors/offline": typeof ErrorsOfflineRoute;
  "/product-description/new": typeof ProductDescriptionNewRoute;
  "/product-export/$id": typeof ProductExportIdRoute;
  "/product-export/new": typeof ProductExportNewRoute;
  "/product-description/": typeof ProductDescriptionIndexRoute;
  "/product-export/": typeof ProductExportIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/errors/403"
    | "/errors/404"
    | "/errors/500"
    | "/errors/offline"
    | "/product-description/new"
    | "/product-export/$id"
    | "/product-export/new"
    | "/product-description/"
    | "/product-export/"
    | "/settings/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/errors/403"
    | "/errors/404"
    | "/errors/500"
    | "/errors/offline"
    | "/product-description/new"
    | "/product-export/$id"
    | "/product-export/new"
    | "/product-description"
    | "/product-export"
    | "/settings";
  id:
    | "__root__"
    | "/"
    | "/errors/403"
    | "/errors/404"
    | "/errors/500"
    | "/errors/offline"
    | "/product-description/new"
    | "/product-export/$id"
    | "/product-export/new"
    | "/product-description/"
    | "/product-export/"
    | "/settings/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  Errors403Route: typeof Errors403Route;
  Errors404Route: typeof Errors404Route;
  Errors500Route: typeof Errors500Route;
  ErrorsOfflineRoute: typeof ErrorsOfflineRoute;
  ProductDescriptionNewRoute: typeof ProductDescriptionNewRoute;
  ProductExportIdRoute: typeof ProductExportIdRoute;
  ProductExportNewRoute: typeof ProductExportNewRoute;
  ProductDescriptionIndexRoute: typeof ProductDescriptionIndexRoute;
  ProductExportIndexRoute: typeof ProductExportIndexRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/product-export/": {
      id: "/product-export/";
      path: "/product-export";
      fullPath: "/product-export/";
      preLoaderRoute: typeof ProductExportIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/product-description/": {
      id: "/product-description/";
      path: "/product-description";
      fullPath: "/product-description/";
      preLoaderRoute: typeof ProductDescriptionIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/product-export/new": {
      id: "/product-export/new";
      path: "/product-export/new";
      fullPath: "/product-export/new";
      preLoaderRoute: typeof ProductExportNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/product-export/$id": {
      id: "/product-export/$id";
      path: "/product-export/$id";
      fullPath: "/product-export/$id";
      preLoaderRoute: typeof ProductExportIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/product-description/new": {
      id: "/product-description/new";
      path: "/product-description/new";
      fullPath: "/product-description/new";
      preLoaderRoute: typeof ProductDescriptionNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/errors/offline": {
      id: "/errors/offline";
      path: "/errors/offline";
      fullPath: "/errors/offline";
      preLoaderRoute: typeof ErrorsOfflineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/errors/500": {
      id: "/errors/500";
      path: "/errors/500";
      fullPath: "/errors/500";
      preLoaderRoute: typeof Errors500RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/errors/404": {
      id: "/errors/404";
      path: "/errors/404";
      fullPath: "/errors/404";
      preLoaderRoute: typeof Errors404RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/errors/403": {
      id: "/errors/403";
      path: "/errors/403";
      fullPath: "/errors/403";
      preLoaderRoute: typeof Errors403RouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
  ErrorsOfflineRoute: ErrorsOfflineRoute,
  ProductDescriptionNewRoute: ProductDescriptionNewRoute,
  ProductExportIdRoute: ProductExportIdRoute,
  ProductExportNewRoute: ProductExportNewRoute,
  ProductDescriptionIndexRoute: ProductDescriptionIndexRoute,
  ProductExportIndexRoute: ProductExportIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
